/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SocialGuestbook } from "./SocialGuestbook";
export * as factories from "./factories";
export { SocialGuestbook__factory } from "./factories/SocialGuestbook__factory";
