/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace SocialGuestbook {
  export type CommentStruct = {
    author: AddressLike;
    text: string;
    timestamp: BigNumberish;
  };

  export type CommentStructOutput = [
    author: string,
    text: string,
    timestamp: bigint
  ] & { author: string; text: string; timestamp: bigint };
}

export interface SocialGuestbookInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_COMMENTS_PER_POST"
      | "MAX_COMMENT_LENGTH"
      | "addressToProfile"
      | "commentOnPost"
      | "createPost"
      | "deletePost"
      | "getCommentCount"
      | "getComments"
      | "getPost"
      | "getProfile"
      | "hasLiked"
      | "likePost"
      | "owner"
      | "postCount"
      | "postingFee"
      | "posts"
      | "registerUser"
      | "setPostingFee"
      | "tipAuthor"
      | "usernameToAddress"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CommentAdded"
      | "PostCreated"
      | "PostDeleted"
      | "PostLiked"
      | "PostingFeeUpdated"
      | "TipSent"
      | "UserRegistered"
      | "Withdrawal"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_COMMENTS_PER_POST",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_COMMENT_LENGTH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addressToProfile",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "commentOnPost",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "createPost", values: [string]): string;
  encodeFunctionData(
    functionFragment: "deletePost",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCommentCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getComments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPost",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProfile",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasLiked",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "likePost",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "postCount", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "postingFee",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "posts", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "registerUser",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setPostingFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tipAuthor",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "usernameToAddress",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "MAX_COMMENTS_PER_POST",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_COMMENT_LENGTH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addressToProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "commentOnPost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createPost", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deletePost", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCommentCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getComments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPost", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getProfile", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasLiked", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "likePost", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "postCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "postingFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "posts", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPostingFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tipAuthor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "usernameToAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace CommentAddedEvent {
  export type InputTuple = [
    postId: BigNumberish,
    author: AddressLike,
    text: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    postId: bigint,
    author: string,
    text: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    postId: bigint;
    author: string;
    text: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PostCreatedEvent {
  export type InputTuple = [
    postId: BigNumberish,
    author: AddressLike,
    content: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    postId: bigint,
    author: string,
    content: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    postId: bigint;
    author: string;
    content: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PostDeletedEvent {
  export type InputTuple = [postId: BigNumberish, deletedBy: AddressLike];
  export type OutputTuple = [postId: bigint, deletedBy: string];
  export interface OutputObject {
    postId: bigint;
    deletedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PostLikedEvent {
  export type InputTuple = [postId: BigNumberish, liker: AddressLike];
  export type OutputTuple = [postId: bigint, liker: string];
  export interface OutputObject {
    postId: bigint;
    liker: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PostingFeeUpdatedEvent {
  export type InputTuple = [oldFee: BigNumberish, newFee: BigNumberish];
  export type OutputTuple = [oldFee: bigint, newFee: bigint];
  export interface OutputObject {
    oldFee: bigint;
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TipSentEvent {
  export type InputTuple = [
    postId: BigNumberish,
    tipper: AddressLike,
    author: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    postId: bigint,
    tipper: string,
    author: string,
    amount: bigint
  ];
  export interface OutputObject {
    postId: bigint;
    tipper: string;
    author: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserRegisteredEvent {
  export type InputTuple = [user: AddressLike, username: string];
  export type OutputTuple = [user: string, username: string];
  export interface OutputObject {
    user: string;
    username: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalEvent {
  export type InputTuple = [owner: AddressLike, amount: BigNumberish];
  export type OutputTuple = [owner: string, amount: bigint];
  export interface OutputObject {
    owner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SocialGuestbook extends BaseContract {
  connect(runner?: ContractRunner | null): SocialGuestbook;
  waitForDeployment(): Promise<this>;

  interface: SocialGuestbookInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_COMMENTS_PER_POST: TypedContractMethod<[], [bigint], "view">;

  MAX_COMMENT_LENGTH: TypedContractMethod<[], [bigint], "view">;

  addressToProfile: TypedContractMethod<
    [arg0: AddressLike],
    [[string, boolean] & { username: string; exists: boolean }],
    "view"
  >;

  commentOnPost: TypedContractMethod<
    [_postId: BigNumberish, _text: string],
    [void],
    "nonpayable"
  >;

  createPost: TypedContractMethod<[_content: string], [void], "payable">;

  deletePost: TypedContractMethod<
    [_postId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getCommentCount: TypedContractMethod<
    [_postId: BigNumberish],
    [bigint],
    "view"
  >;

  getComments: TypedContractMethod<
    [_postId: BigNumberish],
    [SocialGuestbook.CommentStructOutput[]],
    "view"
  >;

  getPost: TypedContractMethod<
    [_postId: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, boolean] & {
        id: bigint;
        author: string;
        content: string;
        timestamp: bigint;
        likeCount: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  getProfile: TypedContractMethod<
    [_user: AddressLike],
    [[string, boolean] & { username: string; exists: boolean }],
    "view"
  >;

  hasLiked: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  likePost: TypedContractMethod<[_postId: BigNumberish], [void], "nonpayable">;

  owner: TypedContractMethod<[], [string], "view">;

  postCount: TypedContractMethod<[], [bigint], "view">;

  postingFee: TypedContractMethod<[], [bigint], "view">;

  posts: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, boolean] & {
        id: bigint;
        author: string;
        content: string;
        timestamp: bigint;
        likeCount: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  registerUser: TypedContractMethod<[_username: string], [void], "nonpayable">;

  setPostingFee: TypedContractMethod<
    [_newFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  tipAuthor: TypedContractMethod<[_postId: BigNumberish], [void], "payable">;

  usernameToAddress: TypedContractMethod<[arg0: string], [string], "view">;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_COMMENTS_PER_POST"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_COMMENT_LENGTH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addressToProfile"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [[string, boolean] & { username: string; exists: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "commentOnPost"
  ): TypedContractMethod<
    [_postId: BigNumberish, _text: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createPost"
  ): TypedContractMethod<[_content: string], [void], "payable">;
  getFunction(
    nameOrSignature: "deletePost"
  ): TypedContractMethod<[_postId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getCommentCount"
  ): TypedContractMethod<[_postId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getComments"
  ): TypedContractMethod<
    [_postId: BigNumberish],
    [SocialGuestbook.CommentStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPost"
  ): TypedContractMethod<
    [_postId: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, boolean] & {
        id: bigint;
        author: string;
        content: string;
        timestamp: bigint;
        likeCount: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProfile"
  ): TypedContractMethod<
    [_user: AddressLike],
    [[string, boolean] & { username: string; exists: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasLiked"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "likePost"
  ): TypedContractMethod<[_postId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "postCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "postingFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "posts"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, boolean] & {
        id: bigint;
        author: string;
        content: string;
        timestamp: bigint;
        likeCount: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerUser"
  ): TypedContractMethod<[_username: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPostingFee"
  ): TypedContractMethod<[_newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tipAuthor"
  ): TypedContractMethod<[_postId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "usernameToAddress"
  ): TypedContractMethod<[arg0: string], [string], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "CommentAdded"
  ): TypedContractEvent<
    CommentAddedEvent.InputTuple,
    CommentAddedEvent.OutputTuple,
    CommentAddedEvent.OutputObject
  >;
  getEvent(
    key: "PostCreated"
  ): TypedContractEvent<
    PostCreatedEvent.InputTuple,
    PostCreatedEvent.OutputTuple,
    PostCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PostDeleted"
  ): TypedContractEvent<
    PostDeletedEvent.InputTuple,
    PostDeletedEvent.OutputTuple,
    PostDeletedEvent.OutputObject
  >;
  getEvent(
    key: "PostLiked"
  ): TypedContractEvent<
    PostLikedEvent.InputTuple,
    PostLikedEvent.OutputTuple,
    PostLikedEvent.OutputObject
  >;
  getEvent(
    key: "PostingFeeUpdated"
  ): TypedContractEvent<
    PostingFeeUpdatedEvent.InputTuple,
    PostingFeeUpdatedEvent.OutputTuple,
    PostingFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TipSent"
  ): TypedContractEvent<
    TipSentEvent.InputTuple,
    TipSentEvent.OutputTuple,
    TipSentEvent.OutputObject
  >;
  getEvent(
    key: "UserRegistered"
  ): TypedContractEvent<
    UserRegisteredEvent.InputTuple,
    UserRegisteredEvent.OutputTuple,
    UserRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawal"
  ): TypedContractEvent<
    WithdrawalEvent.InputTuple,
    WithdrawalEvent.OutputTuple,
    WithdrawalEvent.OutputObject
  >;

  filters: {
    "CommentAdded(uint256,address,string,uint256)": TypedContractEvent<
      CommentAddedEvent.InputTuple,
      CommentAddedEvent.OutputTuple,
      CommentAddedEvent.OutputObject
    >;
    CommentAdded: TypedContractEvent<
      CommentAddedEvent.InputTuple,
      CommentAddedEvent.OutputTuple,
      CommentAddedEvent.OutputObject
    >;

    "PostCreated(uint256,address,string,uint256)": TypedContractEvent<
      PostCreatedEvent.InputTuple,
      PostCreatedEvent.OutputTuple,
      PostCreatedEvent.OutputObject
    >;
    PostCreated: TypedContractEvent<
      PostCreatedEvent.InputTuple,
      PostCreatedEvent.OutputTuple,
      PostCreatedEvent.OutputObject
    >;

    "PostDeleted(uint256,address)": TypedContractEvent<
      PostDeletedEvent.InputTuple,
      PostDeletedEvent.OutputTuple,
      PostDeletedEvent.OutputObject
    >;
    PostDeleted: TypedContractEvent<
      PostDeletedEvent.InputTuple,
      PostDeletedEvent.OutputTuple,
      PostDeletedEvent.OutputObject
    >;

    "PostLiked(uint256,address)": TypedContractEvent<
      PostLikedEvent.InputTuple,
      PostLikedEvent.OutputTuple,
      PostLikedEvent.OutputObject
    >;
    PostLiked: TypedContractEvent<
      PostLikedEvent.InputTuple,
      PostLikedEvent.OutputTuple,
      PostLikedEvent.OutputObject
    >;

    "PostingFeeUpdated(uint256,uint256)": TypedContractEvent<
      PostingFeeUpdatedEvent.InputTuple,
      PostingFeeUpdatedEvent.OutputTuple,
      PostingFeeUpdatedEvent.OutputObject
    >;
    PostingFeeUpdated: TypedContractEvent<
      PostingFeeUpdatedEvent.InputTuple,
      PostingFeeUpdatedEvent.OutputTuple,
      PostingFeeUpdatedEvent.OutputObject
    >;

    "TipSent(uint256,address,address,uint256)": TypedContractEvent<
      TipSentEvent.InputTuple,
      TipSentEvent.OutputTuple,
      TipSentEvent.OutputObject
    >;
    TipSent: TypedContractEvent<
      TipSentEvent.InputTuple,
      TipSentEvent.OutputTuple,
      TipSentEvent.OutputObject
    >;

    "UserRegistered(address,string)": TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
    UserRegistered: TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;

    "Withdrawal(address,uint256)": TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;
    Withdrawal: TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;
  };
}
